import * as crypto from "node:crypto";
import * as fs from "node:fs";
import * as path from "node:path";

import * as mcThailand from "../data/mc-thailand";
import * as nlm from "../data/nlm";

const PASSWORD = "iDip";
const PBKDF2_ITERATIONS = 100_000;

const datasets = [
  { label: mcThailand.label, dimensions: mcThailand.dimensions, projects: mcThailand.projects },
  { label: nlm.label, dimensions: nlm.dimensions, projects: nlm.projects },
];

// One salt for the whole file, separate IV per dataset
const salt = crypto.randomBytes(16);
const key = crypto.pbkdf2Sync(PASSWORD, salt, PBKDF2_ITERATIONS, 32, "sha256");
const passwordHash = crypto.createHash("sha256").update(PASSWORD).digest("hex");

const encrypted = datasets.map((ds) => {
  const iv = crypto.randomBytes(12);
  const cipher = crypto.createCipheriv("aes-256-gcm", key, iv);
  const json = JSON.stringify({ label: ds.label, dimensions: ds.dimensions, projects: ds.projects });
  const enc = Buffer.concat([cipher.update(json, "utf8"), cipher.final()]);
  const tag = cipher.getAuthTag();
  // Web Crypto AES-GCM expects ciphertext+tag concatenated
  return {
    iv: iv.toString("base64"),
    data: Buffer.concat([enc, tag]).toString("base64"),
  };
});

const output = `// AUTO-GENERATED by scripts/encrypt-data.ts — do not edit manually
// Re-generate with: npm run encrypt-data

export const ENCRYPTION_SALT = "${salt.toString("base64")}";
export const PASSWORD_HASH = "${passwordHash}";
export const PBKDF2_ITERATIONS = ${PBKDF2_ITERATIONS};

export const ENCRYPTED_DATASETS: { iv: string; data: string }[] = ${JSON.stringify(encrypted, null, 2)};
`;

const outPath = path.resolve(__dirname, "..", "src", "app", "portfolio-list", "encrypted-data.ts");
fs.writeFileSync(outPath, output);
console.log(`Wrote encrypted data to ${outPath}`);
